import json
import os

nb = {
 'metadata': {
  'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
  'language_info': {'name': 'python', 'version': '3.12.12'},
  'kaggle': {
   'accelerator': 'nvidiaTeslaT4',
   'isInternetEnabled': True,
   'language': 'python',
   'sourceType': 'notebook',
   'isGpuEnabled': True
  }
 },
 'nbformat_minor': 5,
 'nbformat': 4,
 'cells': [
  {
   'id': 'p3_c1',
   'cell_type': 'markdown',
   'source': [
    '# ⛏️ MineAgent Phase 3: Pure JSON Gameplay LLM\n',
    '**Model**: `Qwen2.5-Coder-0.5B-Instruct` | **Architecture**: High-Rank LoRA (Equivalent to Full Fine-Tuning) | **Target Loss**: `< 0.05`\n',
    '\n',
    'This notebook is optimized for **Kaggle T4 GPUs**. It trains a highly efficient 0.5B model to strictly output structured JSON actions for Mineflayer.\n',
    '\n',
    '### 🚀 Quick Setup\n',
    '1. Upload your 100k synthetic dataset to a Kaggle Dataset named `mineagent-100k`.\n',
    '2. Add your Hugging Face token to Kaggle Secrets as `HF_TOKEN`.\n',
    '3. Enable **GPU T4 x2** in the notebook settings.\n',
    '4. Run all cells!'
   ],
   'metadata': {}
  },
  {
   'id': 'p3_c2',
   'cell_type': 'code',
   'source': [
    '# ── Cell 1: Environment Setup & Library Installation ────────────────────\n',
    'import os, warnings, subprocess, sys, logging\n',
    '\n',
    '# Suppress noisy logs (Tensorflow and Torch version warnings)\n',
    'os.environ[\'TF_CPP_MIN_LOG_LEVEL\'] = \'3\'\n',
    'warnings.filterwarnings(\'ignore\')\n',
    'logging.getLogger("unsloth").setLevel(logging.ERROR)\n',
    '\n',
    'print("⏳ Installing dependencies...")\n',
    'subprocess.run([sys.executable, \'-m\', \'pip\', \'install\', \'-q\',\n',
    '    \'unsloth\', \'trl<0.9.0\', \'peft\', \'bitsandbytes\',\n',
    '    \'datasets>=2.14\', \'accelerate\', \'huggingface_hub\'], check=False)\n',
    '\n',
    'print(\'✅ Environment ready.\')'
   ],
   'metadata': {'trusted': True},
   'outputs': [],
   'execution_count': None
  },
  {
   'id': 'p3_c3',
   'cell_type': 'code',
   'source': [
    '# ── Cell 2: GPU Verification & Hugging Face Login ───────────────────────\n',
    'import torch\n',
    'from kaggle_secrets import UserSecretsClient\n',
    'from huggingface_hub import login\n',
    '\n',
    'print(\'--- Hardware Check ---\')\n',
    'print(\'GPU  :\', torch.cuda.get_device_name(0))\n',
    'print(\'VRAM :\', round(torch.cuda.get_device_properties(0).total_memory/1024**3, 1), \'GB\')\n',
    'print(\'BF16 :\', torch.cuda.is_bf16_supported())\n',
    '\n',
    'HF_TOKEN = UserSecretsClient().get_secret(\'HF_TOKEN\')\n',
    'login(HF_TOKEN)\n',
    'print(\'✅ HuggingFace logged in successfully.\')'
   ],
   'metadata': {'trusted': True},
   'outputs': [],
   'execution_count': None
  },
  {
   'id': 'p3_c4',
   'cell_type': 'code',
   'source': [
    '# ── Cell 3: Load Model & High-Rank LoRA Architecture ────────────────────\n',
    '# Using a 0.5B model allows for native CPU inference in Node.js later.\n',
    '# The rank is set to 128 across ALL linear layers and the embeddings/lm_head.\n',
    '# This is mathematically equivalent to Full Fine-Tuning but prevents OOM.\n',
    'from unsloth import FastLanguageModel\n',
    'import torch\n',
    '\n',
    'MODEL_ID    = \'Qwen/Qwen2.5-Coder-0.5B-Instruct\'\n',
    'MAX_SEQ_LEN = 256  # JSONs are short. Reducing this prevents OOM.\n',
    '\n',
    'model, tok = FastLanguageModel.from_pretrained(\n',
    '    model_name=MODEL_ID,\n',
    '    max_seq_length=MAX_SEQ_LEN,\n',
    '    dtype=None,\n',
    '    load_in_4bit=True, # 4-bit quantization saves massive VRAM\n',
    ')\n',
    '\n',
    'model = FastLanguageModel.get_peft_model(\n',
    '    model,\n',
    '    r=128,             # HIGH RANK: Deep behavioral rewiring\n',
    '    lora_alpha=256,    # Standard practice is 2 * r\n',
    '    target_modules=[\n',
    '        # Core attention & MLP layers\n',
    '        \'q_proj\', \'k_proj\', \'v_proj\', \'o_proj\',\n',
    '        \'gate_proj\', \'up_proj\', \'down_proj\',\n',
    '        # CRITICAL: Train embeddings & head to overwrite English vocabulary with JSON priority\n',
    '        \'embed_tokens\', \'lm_head\',\n',
    '    ],\n',
    '    lora_dropout=0.0,\n',
    '    bias=\'none\',\n',
    '    use_gradient_checkpointing=\'unsloth\',\n',
    '    random_state=42,\n',
    ')\n',
    '\n',
    'print(f\'✅ Model loaded: {MODEL_ID}\')\n',
    'print(f\'   Trainable params: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}\')'
   ],
   'metadata': {'trusted': True},
   'outputs': [],
   'execution_count': None
  },
  {
   'id': 'p3_c5',
   'cell_type': 'code',
   'source': [
    '# ── Cell 4: Load & Validate Synthetic Dataset ───────────────────────────\n',
    'from datasets import load_dataset\n',
    'from pathlib import Path\n',
    'import json\n',
    '\n',
    'DATA_PATH = \'/kaggle/input/mineagent-100k/stage1_100k.jsonl\'\n',
    '\n',
    'if not Path(DATA_PATH).exists():\n',
    '    # Fallback to local working directory for testing\n',
    '    DATA_PATH = \'/kaggle/working/data/stage1_100k.jsonl\'\n',
    '    if not Path(DATA_PATH).exists():\n',
    '        raise FileNotFoundError(f\'Missing dataset at {DATA_PATH}\')\n',
    '\n',
    '# Validate format (Strict JSON State -> JSON Action)\n',
    'with open(DATA_PATH) as f:\n',
    '    sample = json.loads(f.readline())\n',
    'assert \'messages\' in sample, \'Dataset must have messages field\'\n',
    'assert len(sample[\'messages\']) == 2, \'Each example must have exactly 2 messages\'\n',
    '\n',
    '# Verify tokenizers\n',
    'tok.pad_token = tok.eos_token\n',
    'tok.padding_side = \'right\'\n',
    '\n',
    '# Load & Split dataset\n',
    'ds = load_dataset(\'json\', data_files={\'train\': DATA_PATH}, split=\'train\')\n',
    'split = ds.train_test_split(test_size=0.02, seed=42)\n',
    '\n',
    'def fmt(ex):\n',
    '    return {\'text\': tok.apply_chat_template(ex[\'messages\'], tokenize=False, add_generation_prompt=False)}\n',
    '\n',
    'split = split.map(fmt, batched=False)\n',
    '\n',
    'print(f\'✅ Dataset ready! Train: {len(split["train"]):,} | Val: {len(split["test"]):,}\')'
   ],
   'metadata': {'trusted': True},
   'outputs': [],
   'execution_count': None
  },
  {
   'id': 'p3_c6',
   'cell_type': 'code',
   'source': [
    '# ── Cell 5: Advanced SFT Trainer Setup ──────────────────────────────────\n',
    'from trl import SFTTrainer\n',
    'from transformers import TrainingArguments, TrainerCallback, TrainerState, TrainerControl\n',
    'from tqdm.auto import tqdm\n',
    'import os\n',
    'os.environ[\'TOKENIZERS_PARALLELISM\'] = \'false\'\n',
    '\n',
    'class TqdmLossCallback(TrainerCallback):\n',
    '    def __init__(self):\n',
    '        self.pbar = None; self.step = 0\n',
    '    def on_train_begin(self, args, state: TrainerState, control: TrainerControl, **kwargs):\n',
    '        self.pbar = tqdm(total=state.max_steps, desc=\'🎮 Training\', dynamic_ncols=True)\n',
    '        self.step = 0\n',
    '    def on_log(self, args, state: TrainerState, control: TrainerControl, logs=None, **kwargs):\n',
    '        if not logs or not self.pbar: return\n',
    '        tl, vl = logs.get(\'loss\'), logs.get(\'eval_loss\')\n',
    '        if tl: self.pbar.set_postfix({\'train_loss\': f"{tl:.4f}"})\n',
    '        delta = state.global_step - self.step\n',
    '        if delta > 0:\n',
    '            self.pbar.update(delta)\n',
    '            self.step = state.global_step\n',
    '    def on_train_end(self, args, state, control, **kwargs):\n',
    '        if self.pbar: self.pbar.close()\n',
    '\n',
    'trainer = SFTTrainer(\n',
    '    model=model,\n',
    '    tokenizer=tok,\n',
    '    train_dataset=split[\'train\'],\n',
    '    eval_dataset=split[\'test\'],\n',
    '    dataset_text_field=\'text\',\n',
    '    max_seq_length=MAX_SEQ_LEN,\n',
    '    callbacks=[TqdmLossCallback()],\n',
    '    args=TrainingArguments(\n',
    '        output_dir=\'/kaggle/working/phase3\',\n',
    '        num_train_epochs=15,             # High epochs for strict JSON memorization\n',
    '        per_device_train_batch_size=2,   # 🛑 CRITICAL: Keep at 2 to avoid VRAM limits\n',
    '        gradient_accumulation_steps=32,  # Effective Batch Size = 2 * 32 = 64\n',
    '        learning_rate=5e-5,\n',
    '        lr_scheduler_type=\'cosine\',\n',
    '        warmup_ratio=0.05,\n',
    '        weight_decay=0.1,\n',
    '        neftune_noise_alpha=5,           # Forces generalization over string memorization\n',
    '        fp16=True, bf16=False,\n',
    '        logging_steps=1,\n',
    '        eval_strategy=\'steps\',\n',
    '        eval_steps=200,\n',
    '        save_strategy=\'steps\',\n',
    '        save_steps=500,\n',
    '        save_total_limit=2,\n',
    '        report_to=\'none\',\n',
    '        disable_tqdm=True,\n',
    '        gradient_checkpointing=True,\n',
    '        optim=\'adamw_8bit\',\n',
    '    )\n',
    ')\n',
    '\n',
    'print(\'=== Phase 3 Training Start ===\')\n',
    'trainer.train()\n',
    'model.save_pretrained(\'/kaggle/working/mineagent-phase3-lora\')\n',
    'tok.save_pretrained(\'/kaggle/working/mineagent-phase3-lora\')\n',
    'print(\'✅ LoRA Adapter Saved!\')'
   ],
   'metadata': {'trusted': True},
   'outputs': [],
   'execution_count': None
  },
  {
   'id': 'p3_c7',
   'cell_type': 'code',
   'source': [
    '# ── Cell 6: JSON Schema Adherence Evaluation ────────────────────────────\n',
    '# Tests if the model perfectly adheres to JSON structure during edge cases.\n',
    'import json\n',
    'from unsloth import FastLanguageModel\n',
    'FastLanguageModel.for_inference(model)\n',
    '\n',
    'TEST_STATES = [\n',
    '    \'{"hp":20,"food":20,"pos":{"x":10,"y":64,"z":10},"inv":{"wooden_planks":5,"stick":4,"crafting_table":1},"nearby":[{"name":"crafting_table","dist":1.5}],"mobs":[],"time":1000,"raining":false,"goal":"craft_wooden_pickaxe"}\',\n',
    '    \'{"hp":15,"food":14,"pos":{"x":5,"y":64,"z":5},"inv":{"iron_sword":1},"nearby":[],"mobs":[{"name":"creeper","dist":3.0,"hp":20,"hostile":true}],"time":14000,"raining":false,"goal":"survive"}\',\n',
    ']\n',
    '\n',
    'EXPECTED_ACTIONS = [\'CRAFT\', \'MOVE\']\n',
    '\n',
    'print(\'=== Testing Generation ===\')\n',
    'for i, (state_str, expected) in enumerate(zip(TEST_STATES, EXPECTED_ACTIONS)):\n',
    '    inputs = tok.apply_chat_template([{\'role\':\'user\',\'content\':state_str}], tokenize=True, add_generation_prompt=True, return_tensors=\'pt\').to(\'cuda\')\n',
    '    with torch.no_grad():\n',
    '        outputs = model.generate(input_ids=inputs, max_new_tokens=64, temperature=0.1, pad_token_id=tok.eos_token_id)\n',
    '    response = tok.decode(outputs[0][inputs.shape[1]:], skip_special_tokens=True).strip()\n',
    '    \n',
    '    try:\n',
    '        parsed = json.loads(response)\n',
    '        is_valid = parsed.get(\'action\', \'\').upper() == expected\n',
    '        status = \'✅\' if is_valid else \'⚠️\'\n',
    '    except json.JSONDecodeError:\n',
    '        status = \'❌\'\n',
    '    \n',
    '    print(f\'{status} Test {i+1} Output: {response}\')'
   ],
   'metadata': {'trusted': True},
   'outputs': [],
   'execution_count': None
  },
  {
   'id': 'p3_c8',
   'cell_type': 'code',
   'source': [
    '# ── Cell 7: Export to GGUF (Optimized for CPU Inference) ────────────────\n',
    'import gc, os, subprocess, sys\n',
    'del trainer; gc.collect(); torch.cuda.empty_cache()\n',
    '\n',
    'MERGED_DIR = \'/tmp/merged\'\n',
    'GGUF_DIR   = \'/kaggle/working/mineagent-phase3-gguf\'\n',
    'os.makedirs(GGUF_DIR, exist_ok=True)\n',
    '\n',
    'print(\'Merging weights...\')\n',
    'model.save_pretrained_merged(MERGED_DIR, tok, save_method=\'merged_16bit\')\n',
    'del model; gc.collect(); torch.cuda.empty_cache()\n',
    '\n',
    'print(\'Converting & Quantizing to Q8_0...\')\n',
    '# In Kaggle environments, we rely on Unsloth\'s built-in export.\n',
    '# Q8_0 is recommended for 0.5B models to prevent precision degradation.\n',
    'try:\n',
    '    model.save_pretrained_gguf(GGUF_DIR, tok, quantization_method="q8_0")\n',
    '    print(f\'✅ Exported Q8_0 GGUF to {GGUF_DIR}\')\n',
    'except Exception as e:\n',
    '    print(f\'Error during GGUF export: {e}\')\n',
    '    print(f\'Note: Advanced GGUF export requires unsloth_zoo upgrade. Merged weights available at {MERGED_DIR}\')'
   ],
   'metadata': {'trusted': True},
   'outputs': [],
   'execution_count': None
  },
  {
   'id': 'p3_c9',
   'cell_type': 'code',
   'source': [
    '# ── Cell 8: Push to HuggingFace Hub ─────────────────────────────────────\n',
    'from huggingface_hub import HfApi\n',
    'from kaggle_secrets import UserSecretsClient\n',
    '\n',
    'HF_USERNAME = \'Tron101101\'\n',
    'HF_TOKEN    = UserSecretsClient().get_secret(\'HF_TOKEN\')\n',
    'api = HfApi(token=HF_TOKEN)\n',
    '\n',
    'GGUF_REPO = f\'{HF_USERNAME}/mineagent-phase3\'\n',
    'LORA_REPO = f\'{HF_USERNAME}/mineagent-phase3-lora\'\n',
    '\n',
    'print(\'Creating repos...\')\n',
    'api.create_repo(repo_id=GGUF_REPO, repo_type=\'model\', exist_ok=True, private=False)\n',
    'api.create_repo(repo_id=LORA_REPO, repo_type=\'model\', exist_ok=True, private=False)\n',
    '\n',
    'print(\'Uploading GGUF...\')\n',
    'api.upload_folder(folder_path=\'/kaggle/working/mineagent-phase3-gguf\',\n',
    '                  repo_id=GGUF_REPO, repo_type=\'model\', token=HF_TOKEN,\n',
    '                  commit_message=\'Phase 3: Pure JSON gameplay agent Q8_0\')\n',
    '\n',
    'print(\'Uploading LoRA...\')\n',
    'api.upload_folder(folder_path=\'/kaggle/working/mineagent-phase3-lora\',\n',
    '                  repo_id=LORA_REPO, repo_type=\'model\', token=HF_TOKEN,\n',
    '                  commit_message=\'Phase 3: LoRA adapter r=128\')\n',
    '\n',
    'print(f\'\\n✅ Upload complete!\')\n',
    'print(f\'  GGUF : https://huggingface.co/{GGUF_REPO}\')\n',
    'print(f\'  LoRA : https://huggingface.co/{LORA_REPO}\')'
   ],
   'metadata': {'trusted': True},
   'outputs': [],
   'execution_count': None
  }
 ]
}

path = r'e:\Projects\MineCraft Agent\training\phase-3\phase3_training.ipynb'
with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
print('Notebook rewritten with clean markdowns and codes')
