"""
patch_notebook.py — Fixes HF dataset issues
Run: python training/patch_notebook.py
"""
import json
from pathlib import Path

nb_path = Path("training/mineagent_train.ipynb")
nb = json.loads(nb_path.read_text(encoding="utf-8"))

CELL3_NEW = [
    "# ── Cell 3: Collect Training Data ───────────────────────────────\n",
    "import json, time, random, requests, os\n",
    "from pathlib import Path\n",
    "from datasets import load_dataset\n",
    "\n",
    "Path('/kaggle/working/data').mkdir(exist_ok=True)\n",
    "\n",
    "SYS_KNOW = 'You are MineAgent, an expert Minecraft AI. Answer accurately about Minecraft.'\n",
    "SYS_ACT  = 'You are MineAgent. Output ONLY valid JSON: {\"action\":\"NAME\",\"params\":{},\"reasoning\":\"\"}'\n",
    "\n",
    "def qa_chat(q, a, sys=None):\n",
    "    return {'messages':[{'role':'system','content':sys or SYS_KNOW},\n",
    "                        {'role':'user','content':q},\n",
    "                        {'role':'assistant','content':a}]}\n",
    "\n",
    "def save(path, data):\n",
    "    with open(path,'w') as f:\n",
    "        [f.write(json.dumps(x)+'\\n') for x in data]\n",
    "    print(f'Saved {len(data)} -> {path}')\n",
    "\n",
    "# ── Source 1: Minecraft Wiki ─────────────────────────────────────\n",
    "def get_wiki(max_pages=400):\n",
    "    API = 'https://minecraft.wiki/api.php'\n",
    "    CATS = ['Blocks','Items','Crafting','Mobs','Biomes','Food',\n",
    "            'Tools','Weapons','Armor','Mechanics']\n",
    "    pairs, seen = [], set()\n",
    "    for cat in CATS:\n",
    "        if len(seen) >= max_pages: break\n",
    "        try:\n",
    "            r = requests.get(API, params={'action':'query','list':'categorymembers',\n",
    "                'cmtitle':f'Category:{cat}','cmlimit':'100','format':'json'}, timeout=15)\n",
    "            for p in r.json()['query']['categorymembers']:\n",
    "                if p['title'] in seen or len(seen) >= max_pages: continue\n",
    "                seen.add(p['title'])\n",
    "                r2 = requests.get(API, params={'action':'query','titles':p['title'],\n",
    "                    'prop':'extracts','explaintext':True,'format':'json'}, timeout=15)\n",
    "                txt = list(r2.json()['query']['pages'].values())[0].get('extract','')[:1000]\n",
    "                if len(txt) < 80: continue\n",
    "                pairs.append(qa_chat(f\"What is {p['title']} in Minecraft?\", txt))\n",
    "                pairs.append(qa_chat(f\"How do you use {p['title']} in Minecraft?\", txt[:500]))\n",
    "                time.sleep(0.1)\n",
    "        except Exception as e:\n",
    "            pass\n",
    "    print(f'Wiki: {len(pairs)} pairs')\n",
    "    return pairs\n",
    "\n",
    "# ── Source 2: Minecraft HF Datasets (Reliable replacements) ──────\n",
    "def get_hf_qa(limit=15000):\n",
    "    pairs = []\n",
    "    try:\n",
    "        # Use reliable public Minecraft Q&A dataset instead of broken MineDojo\n",
    "        ds = load_dataset('naklecha/minecraft-question-answer-700k', split='train', streaming=True)\n",
    "        for item in ds:\n",
    "            if len(pairs) >= limit: break\n",
    "            q = item.get('question','') or item.get('instruction','')\n",
    "            a = item.get('answer','') or item.get('output','')\n",
    "            if len(a) > 20:\n",
    "                pairs.append(qa_chat(q, a[:500]))\n",
    "        print(f'HF Q&A Dataset 1: {len(pairs)} pairs')\n",
    "    except Exception as e:\n",
    "        print(f'Dataset 1 error: {e}')\n",
    "    \n",
    "    try:\n",
    "        ds2 = load_dataset('minhaozhang/minecraft-question-answer-630k', split='train', streaming=True)\n",
    "        for item in ds2:\n",
    "            if len(pairs) >= limit * 1.5: break\n",
    "            q = item.get('question','') or item.get('instruction','')\n",
    "            a = item.get('answer','') or item.get('output','')\n",
    "            if len(a) > 20:\n",
    "                pairs.append(qa_chat(q, a[:500]))\n",
    "        print(f'HF Q&A Dataset 2: {len(pairs)} pairs')\n",
    "    except Exception as e:\n",
    "        print(f'Dataset 2 error: {e}')\n",
    "        \n",
    "    return pairs\n",
    "\n",
    "# ── Source 3: Bot sessions (uploaded as Kaggle dataset input) ────\n",
    "def get_sessions():\n",
    "    path = '/kaggle/input/mineagent-sessions/session_log.jsonl'\n",
    "    if not Path(path).exists():\n",
    "        return []\n",
    "    VALID = {'SEEK','MINE','MOVE','CRAFT','EAT','CHAT','FOLLOW','GOTO','STOP'}\n",
    "    pairs = []\n",
    "    for line in open(path):\n",
    "        item = json.loads(line)\n",
    "        if item.get('source') != 'llm': continue\n",
    "        a = item.get('action',{})\n",
    "        if a.get('action') not in VALID: continue\n",
    "        q = (f\"Goal:{item.get('goal','')} \"\n",
    "             f\"HP:{item.get('player',{}).get('health',20)} \"\n",
    "             f\"Inv:{list(item.get('inventory',{}).keys())[:5]} \"\n",
    "             f\"Nearby:{[b['name'] for b in item.get('nearby_blocks',[])[:5]]} \"\n",
    "             f\"Progress:{item.get('goal_progress','')}\")\n",
    "        out = json.dumps({'action':a['action'],'params':a.get('params',{}),'reasoning':a.get('reasoning','')})\n",
    "        pairs.append(qa_chat(q, out, sys=SYS_ACT))\n",
    "    print(f'Sessions: {len(pairs)} pairs')\n",
    "    return pairs\n",
    "\n",
    "# ── Build datasets ────────────────────────────────────────────────\n",
    "stage1 = get_wiki(max_pages=400)\n",
    "stage1 += get_hf_qa(limit=18000)\n",
    "\n",
    "stage2 = get_sessions()\n",
    "\n",
    "random.shuffle(stage1)\n",
    "random.shuffle(stage2)\n",
    "\n",
    "save('/kaggle/working/data/stage1.jsonl', stage1)\n",
    "save('/kaggle/working/data/stage2.jsonl', stage2)\n",
    "print(f'\\nStage1: {len(stage1)} | Stage2: {len(stage2)}')\n"
]

# Apply patches
for cell in nb["cells"]:
    if cell.get("id") == "c4":
        cell["source"] = CELL3_NEW
        print(f"Patched cell id={cell['id']}")

nb_path.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
print("Saved:", nb_path)
