"""
patch_notebook.py — Fixes install + data collection cells
Run: python training/patch_notebook.py
"""
import json
from pathlib import Path

nb_path = Path("training/mineagent_train.ipynb")
nb = json.loads(nb_path.read_text(encoding="utf-8"))

# ── Cell 1: Install — remove minedojo (needs Java, fails on Kaggle) ──
CELL1 = [
    "import subprocess, sys\n",
    "\n",
    "# Core training libs\n",
    "subprocess.run([sys.executable,'-m','pip','install','-q',\n",
    "    'unsloth','trl==0.11.0','peft==0.12.0',\n",
    "    'bitsandbytes','datasets>=2.14','accelerate',\n",
    "    'huggingface_hub','mwclient','requests'], check=False)\n",
    "\n",
    "# NOTE: minedojo removed — requires Java JDK 8 which is not available on Kaggle\n",
    "# Reddit + YouTube data loaded via HuggingFace datasets API instead\n",
    "print('Install done')",
]

# ── Cell 3: Data collection — fix Reddit/YouTube to use HF datasets ──
CELL3 = [
    "# ── Cell 3: Collect Training Data ───────────────────────────────\n",
    "import json, time, random, requests, os\n",
    "from pathlib import Path\n",
    "from datasets import load_dataset\n",
    "\n",
    "Path('/kaggle/working/data').mkdir(exist_ok=True)\n",
    "\n",
    "SYS_KNOW = 'You are MineAgent, an expert Minecraft AI. Answer accurately about Minecraft.'\n",
    "SYS_ACT  = 'You are MineAgent. Output ONLY valid JSON: {\"action\":\"NAME\",\"params\":{},\"reasoning\":\"\"}'\n",
    "\n",
    "def qa_chat(q, a, sys=None):\n",
    "    return {'messages':[{'role':'system','content':sys or SYS_KNOW},\n",
    "                        {'role':'user','content':q},\n",
    "                        {'role':'assistant','content':a}]}\n",
    "\n",
    "def save(path, data):\n",
    "    with open(path,'w') as f:\n",
    "        [f.write(json.dumps(x)+'\\n') for x in data]\n",
    "    print(f'Saved {len(data)} -> {path}')\n",
    "\n",
    "# ── Source 1: Minecraft Wiki (working) ───────────────────────────\n",
    "def get_wiki(max_pages=600):\n",
    "    API = 'https://minecraft.wiki/api.php'\n",
    "    CATS = ['Blocks','Items','Crafting','Mobs','Biomes','Food',\n",
    "            'Tools','Weapons','Armor','Mechanics','Brewing',\n",
    "            'Enchanting','Structures','Tutorials','Redstone']\n",
    "    pairs, seen = [], set()\n",
    "    for cat in CATS:\n",
    "        if len(seen) >= max_pages: break\n",
    "        try:\n",
    "            r = requests.get(API, params={'action':'query','list':'categorymembers',\n",
    "                'cmtitle':f'Category:{cat}','cmlimit':'100','format':'json'}, timeout=15)\n",
    "            for p in r.json()['query']['categorymembers']:\n",
    "                if p['title'] in seen or len(seen) >= max_pages: continue\n",
    "                seen.add(p['title'])\n",
    "                r2 = requests.get(API, params={'action':'query','titles':p['title'],\n",
    "                    'prop':'extracts','explaintext':True,'format':'json'}, timeout=15)\n",
    "                txt = list(r2.json()['query']['pages'].values())[0].get('extract','')[:1000]\n",
    "                if len(txt) < 80: continue\n",
    "                pairs.append(qa_chat(f\"What is {p['title']} in Minecraft?\", txt))\n",
    "                pairs.append(qa_chat(f\"How do you use {p['title']} in Minecraft?\", txt[:500]))\n",
    "                pairs.append(qa_chat(f\"Tell me about {p['title']}.\", txt[:400]))\n",
    "                time.sleep(0.2)\n",
    "        except Exception as e:\n",
    "            print(f'Wiki cat {cat} error: {e}')\n",
    "    print(f'Wiki: {len(pairs)} pairs from {len(seen)} pages')\n",
    "    return pairs\n",
    "\n",
    "# ── Source 2: Reddit via HuggingFace datasets (no minedojo needed) ──\n",
    "def get_reddit(limit=12000):\n",
    "    KW = ['craft','mine','build','survive','wood','stone','coal',\n",
    "          'iron','diamond','pickaxe','hunger','health','recipe',\n",
    "          'biome','nether','creeper','enchant','farm']\n",
    "    pairs = []\n",
    "    try:\n",
    "        # MineDojo Reddit data via HuggingFace\n",
    "        ds = load_dataset('MineDojo/foundation_model_data', 'reddit',\n",
    "                          split='train', streaming=True, trust_remote_code=True)\n",
    "        for item in ds:\n",
    "            if len(pairs) >= limit: break\n",
    "            t = item.get('title',''); b = item.get('selftext','') or item.get('body','')\n",
    "            if len(b) < 40: continue\n",
    "            if not any(k in (t+b).lower() for k in KW): continue\n",
    "            pairs.append(qa_chat(t, b[:500]))\n",
    "        print(f'Reddit (MineDojo HF): {len(pairs)} pairs')\n",
    "    except Exception as e:\n",
    "        print(f'MineDojo Reddit failed ({e}), trying backup...')\n",
    "        try:\n",
    "            # Backup: general gaming Q&A filtered to Minecraft\n",
    "            ds = load_dataset('sentence-transformers/reddit', split='train',\n",
    "                              streaming=True)\n",
    "            for item in ds:\n",
    "                if len(pairs) >= limit: break\n",
    "                q = item.get('query',''); a = item.get('response','')\n",
    "                if not any(k in (q+a).lower() for k in ['minecraft','mine','craft','creeper']): continue\n",
    "                if len(a) < 40: continue\n",
    "                pairs.append(qa_chat(q, a[:500]))\n",
    "            print(f'Reddit (backup): {len(pairs)} pairs')\n",
    "        except Exception as e2:\n",
    "            print(f'Reddit backup also failed: {e2}')\n",
    "    return pairs\n",
    "\n",
    "# ── Source 3: YouTube via HuggingFace (no minedojo needed) ───────\n",
    "def get_youtube(limit=8000):\n",
    "    KW = ['wood','mine','craft','survive','build','explore','cave',\n",
    "          'diamond','pickaxe','stone','coal','iron','house','farm']\n",
    "    pairs = []\n",
    "    try:\n",
    "        ds = load_dataset('MineDojo/foundation_model_data', 'youtube',\n",
    "                          split='train', streaming=True, trust_remote_code=True)\n",
    "        for item in ds:\n",
    "            if len(pairs) >= limit: break\n",
    "            t  = item.get('title',''); tr = item.get('transcript','')\n",
    "            if len(tr) < 100: continue\n",
    "            if not any(k in t.lower() for k in KW): continue\n",
    "            ws = tr.split()\n",
    "            for i in range(0, min(len(ws),600), 150):\n",
    "                chunk = ' '.join(ws[i:i+150])\n",
    "                if len(chunk) > 60:\n",
    "                    pairs.append(qa_chat(f'Minecraft gameplay: {t}', chunk))\n",
    "        print(f'YouTube: {len(pairs)} pairs')\n",
    "    except Exception as e:\n",
    "        print(f'YouTube skip: {e}')\n",
    "    return pairs\n",
    "\n",
    "# ── Source 4: Bot sessions (uploaded as Kaggle dataset input) ────\n",
    "def get_sessions():\n",
    "    path = '/kaggle/input/mineagent-sessions/session_log.jsonl'\n",
    "    if not Path(path).exists():\n",
    "        print('No session_log.jsonl found in Kaggle dataset input')\n",
    "        return []\n",
    "    VALID = {'SEEK','MINE','MOVE','CRAFT','EAT','CHAT','FOLLOW','GOTO','STOP'}\n",
    "    pairs = []\n",
    "    for line in open(path):\n",
    "        item = json.loads(line)\n",
    "        if item.get('source') != 'llm': continue\n",
    "        a = item.get('action',{})\n",
    "        if a.get('action') not in VALID: continue\n",
    "        q = (f\"Goal:{item.get('goal','')} \"\n",
    "             f\"HP:{item.get('player',{}).get('health',20)} \"\n",
    "             f\"Inv:{list(item.get('inventory',{}).keys())[:5]} \"\n",
    "             f\"Nearby:{[b['name'] for b in item.get('nearby_blocks',[])[:5]]} \"\n",
    "             f\"Progress:{item.get('goal_progress','')}\")\n",
    "        out = json.dumps({'action':a['action'],'params':a.get('params',{}),'reasoning':a.get('reasoning','')})\n",
    "        pairs.append(qa_chat(q, out, sys=SYS_ACT))\n",
    "    print(f'Sessions: {len(pairs)} pairs')\n",
    "    return pairs\n",
    "\n",
    "# ── Build datasets ────────────────────────────────────────────────\n",
    "stage1 = get_wiki(max_pages=600)  # 3 Q&A per page = ~1800 pairs\n",
    "stage1 += get_reddit()\n",
    "stage1 += get_youtube()\n",
    "\n",
    "stage2 = get_sessions()\n",
    "\n",
    "random.shuffle(stage1)\n",
    "random.shuffle(stage2)\n",
    "\n",
    "save('/kaggle/working/data/stage1.jsonl', stage1)\n",
    "save('/kaggle/working/data/stage2.jsonl', stage2)\n",
    "print(f'\\nStage1: {len(stage1)} | Stage2: {len(stage2)}')\n",
    "print('NOTE: Stage2 synthetic examples loaded in Cell 5 automatically')",
]

# Apply patches
patched = {"c2": CELL1, "c4": CELL3}
for cell in nb["cells"]:
    if cell.get("id") in patched:
        cell["source"] = patched[cell["id"]]
        print(f"Patched cell id={cell['id']}")

nb_path.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
print("Saved:", nb_path)
print("\nSummary of fixes:")
print("  Cell 1: removed minedojo (needs Java), kept all training libs")
print("  Cell 3: Reddit/YouTube now use HuggingFace datasets API directly")
print("  Cell 3: Wiki extended to 600 pages x 3 Q&A = ~1800 stage1 pairs")
print("  Cell 5: unchanged — loads synthetic_stage2.jsonl (1500 unique examples)")
